services:
  db:
    image: postgres:15
    container_name: fastapi_postgres
    restart: always
    env_file:
      - app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  web:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/code   
    working_dir: /code
    command: ["/code/start.sh"]

volumes:
  postgres_data:
