"""create quiz table

Revision ID: 651c4fdd3e3c
Revises: b3a7b0312000
Create Date: 2025-10-13 17:37:43.216143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651c4fdd3e3c'
down_revision: Union[str, Sequence[str], None] = 'b3a7b0312000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('passing_criteria', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'passing_criteria')
    # ### end Alembic commands ###
